# Generated by Django 4.1.13 on 2024-04-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Article'), (2, 'Image'), (3, 'Video')]),
        ),
    ]
